import { Inter } from "next/font/google"
import { dbConnect } from "../services/mongo"
import Navbar from "./components/Navbar"
import "./globals.css"
import AuthProvider from "./Providers/AuthProviders"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  dbConnect()
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
